# 애플리케이션 실행 시 일래스틱 빈스토크에서 값을 덮어쓰므로 여기는 삭제
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
jwt:
  issuer: azsx92@gmail.com