spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource: # database 정보 추가
    url: jdbc:h2:mem:testdb
  h2: # h2 콘솔 활성화
    console:
      enabled: true